### ISSUE TITLE
Trouble receiving incoming msgs in bitlbee 

### ISSUE THREAD

**Issue by demure** [hoehermann/purple-signald#10]
Hi again,

It's honestly been a while since I had working incoming msgs in bitlbee via libpurple-signald, but I hadn't gotten around to troubleshooting.... (outgoing has been fine).

I'm currently testing the `automated-upgrade/com.github.turasa-signal-service-java` branch for @thefinn93, and getting incoming msgs like the following in `nc`

```
{
  "type": "message",
  "data": {
    "username": "+ME",
    "source": {
      "number": "+THEM"
    },
    "sourceDevice": 0,
    "type": "UNIDENTIFIED_SENDER",
    "timestamp": 1593111463841,
    "timestampISO": "2020-06-25T18:57:43.841Z",
    "serverTimestamp": 1593111464606,
    "hasLegacyMessage": false,
    "hasContent": true,
    "isUnidentifiedSender": true,
    "dataMessage": {
      "timestamp": 1593111463841,
      "body": "HERE IS TEXT",
      "endSession": false,
      "expiresInSeconds": 0,
      "profileKeyUpdate": false,
      "viewOnce": false
    }
  }
}
{
  "type": "message",
  "data": {
    "username": "+ME",
    "source": {
      "number": "+THEM"
    },
    "sourceDevice": 0,
    "type": "UNIDENTIFIED_SENDER",
    "timestamp": 1593112497592,
    "timestampISO": "2020-06-25T19:14:57.592Z",
    "serverTimestamp": 1593112498215,
    "hasLegacyMessage": false,
    "hasContent": true,
    "isUnidentifiedSender": true,
    "dataMessage": {
      "timestamp": 1593112497592,
      "body": "MORE TEXT HERE",
      "endSession": false,
      "expiresInSeconds": 0,
      "profileKeyUpdate": false,
      "viewOnce": false
    }
  }
}
```

These are both examples of one of my contacts msging me, and they appear to be self contained (no second msg with more data)

Please let me know if there is more info needed, or if I can help troubleshooting.
I also hang out in the signald irc chan on freenode if you would like to ping me.

**Comment by thefinn93** [comment]
There are some protocol changes, i haven't fully documented them yet. You can see the diff in [this merge request](https://gitlab.com/thefinn93/signald/-/merge_requests/14) which may help, but probably best to just test it yourself. I'm available on IRC or here if there are questions. I'm not entirely sure I'm done changing the protocol, but certainly the bulk of the changes is done. Will ping here when I have better documentation on what changed.

**Comment by fancypantalons** [comment]
> There are some protocol changes, i haven't fully documented them yet. You can see the diff in [this merge request](https://gitlab.com/thefinn93/signald/-/merge_requests/14) which may help, but probably best to just test it yourself. I'm available on IRC or here if there are questions. I'm not entirely sure I'm done changing the protocol, but certainly the bulk of the changes is done. Will ping here when I have better documentation on what changed.

I just filed issue #11 to cover adding support for the updated client protocol.

**Comment by fancypantalons** [comment]
> Hi again,
> 
> It's honestly been a while since I had working incoming msgs in bitlbee via libpurple-signald, but I hadn't gotten around to troubleshooting.... (outgoing has been fine).

Have you tried using master libpurple-signald against the current master signald?  I'm running that combination with bitlbee (well, actually, I'm using my own fork that includes issue #8 and issue #9) and I'm sending and receiving messages just fine.

So if you're having issues with *that* combination, there's something else going on here.

And note: there is a known bug in signald that was very recently addressed that lead to things like reactions breaking receipt of messages from signald (while sending would continue to work).

**Comment by fancypantalons** [comment]
@demure Just FYI, if you're still messing around with the protocol upgrade branch of signald, @hoehermann has pulled the compatibility changes into the master branch, which add support for both the old and new signald protocols.

I'm currently running the code to do live testing against the current stable release of signald to ensure there's no surprise regressions.

If you're interesting in helping do some smoke testing with the signald upgrade branch, that'd definitely be appreciated!

**Comment by demure** [comment]
I've pulled the latest signald `automated-upgrade/com.github.turasa-signal-service-java` as well as the latest libpurple-signald, and am seeing a nice improvement. Not only are incoming messages currently working, I am now seeing a group chat both show up, and have the proper name. :)
