### ISSUE TITLE
Add buddy list download (for usage with Bitlbee and more)

### ISSUE THREAD

**Issue by Strykar** [hoehermann/purple-signald#2]
I'm trying to get this plugin to work with [Bitlbee](https://www.bitlbee.org/main.php/news.r.html), which can use most Pidgin/libpurple plugins.

I'm running Arch linux and have the latest Bitlbee installed, which uses libpurple-plugins to connect to different messaging networks like Discord, Telegram, Steam, Skypeweb and more.

I've setup signald, linked it to my phone's Signal account, and I can send messages via `nc` and the recipient receives them fine.
Bitlbee can see the libpurple-signald plugin, and I created a `hehoe-signald` account (in Bitblee) which shows up as connected.
However, I do not see Signal's user/group list or messages sent to me via Bitlbee or in `&hehoe-signald`.

@hoehermann I understand you may have only tested with Pidgin, but I'd be happy to help get this working with Bitlbee.
@EionRobb Any tips on where to start troubleshooting this? Could the lack of persistent rosters cause this?

**Comment by demure** [comment]
Hi, just another user here. I have bitlbee-libpurple, signald, and libpurple-signald working on debian sid.
First, we should probably note the following from libpurple-signald's readme:
> Missing Features
> * signald configuration (i.e. initial number registration)
> * Integrating with the buddy list
> * Proper group chats (right now you can send and receive group messages, but you cannot tell which one of the group members is answering)
> * Anything beyond simple messaging, really

So no buddy list integration yet.

I'll go ahead and add my workflow for renaming a number in biltbe here though, in case that is useful.

```
add hehoe-signald +12223334444
rename _12223334444 name-sig
``` 
(yes, the `add` has a '+', and the `rename` has a '_')

**EDIT**: After reconnecting to signal in bitlblee I often have to reply to a conversation from my phone, after which I can then continue from bitlbee.

**Comment by hoehermann** [comment]
@Strykar Is the information given by demure sufficient for your needs?

**Comment by Strykar** [comment]
@hoehermann Unfortunately, no, but it appears it's not going to be trivial either.

**Comment by hoehermann** [comment]
Can you see what you need? Like for example buddy-list integration (as in "pull known contacts from server")?

**Comment by Strykar** [comment]
@hoehermann Buddy-list integration is what's missing and tedious to setup each time (for each contact) the client (IRC ) application starts.

**Comment by hoehermann** [comment]
I have some time off in August – I might be adding the buddy list integration.  
If you want it sooner, I'd gladly accept your pull request. :)

**Comment by Strykar** [comment]
Oh man that'd be sweet, sounds like even Pidgin users would benefit.
I'm no programmer or I would've gladly sent a PR :)

**Comment by hoehermann** [comment]
Added with https://github.com/hoehermann/libpurple-signald/pull/4.
