### ISSUE TITLE
Always window popup

### ISSUE THREAD

**Issue by Chris56** [hoehermann/purple-signald#23]
When a new message arrives:
Despite the setting to not popup the window the conversation window does appear.
 (Thanks for the addon, I'd love to use pidgin rather than the memory hog sigal)

**Comment by hoehermann** [comment]
Does this happen with incoming messages as well as messages sent by you (from another device)?

**Comment by Chris56** [comment]
With pidgin in tray:
a)
Note to myself on the master: unwanted popup
b)
Note to some third party on the master: unwanted popup after sending on the master

**Comment by hoehermann** [comment]
I assume you mean this setting (`conversations.chat.im.hide_new`):

![hide_conversation_window](https://user-images.githubusercontent.com/838331/115154482-5efd1d00-a07b-11eb-990c-58095bc57745.png)

It has no effect on any protocol I am currently using (Telegram, WhatsApp). Which protocol plug-ins honor this preference? I can probably copy their code.

**Comment by Chris56** [comment]
I have both telegram and signal account.

When (on mint mate desktop) pidgin is minized to the system tray:
a) receive message from telegram: no unwanted popup with the message contents
b) receive message from signal: immediate unwanted popup with the signal message

P.S.: I you happen to not fill in the "Local alias" field while adding a new signal account, you will not see any contacts.

**Comment by hoehermann** [comment]
In a7e4fdd I changed the code to be more traditional – at least for incoming direct messages. Does it help with this issue?

**Comment by hoehermann** [comment]
Closing due to lack of response.
