### ISSUE TITLE
No ack to sender

### ISSUE THREAD

**Issue by Chris56** [hoehermann/purple-signald#24]
When sending to the pidgin signal:
There is no ack that the message has arrived.
And no ack that the message has been displayed.
(Or am I missng a setting?)
Chris

**Comment by hoehermann** [comment]
These signals are handled by the back-end, but indeed not visible in the front-end.

**Comment by hoehermann** [comment]
I don't know if signald currently exposes these events. I put this on the list of requested features for now.

**Comment by hoehermann** [comment]
TODO: Send "mark_read" message.

**Comment by demure** [comment]
> TODO: Send "mark_read" message.

Will this be optional? I'm sure others disable the read receipts like I do.

**Comment by hoehermann** [comment]
Yes, I want to have it optional.
