### ISSUE TITLE
Create IRC channel for the libpurple-signald project

### ISSUE THREAD

**Issue by Strykar** [hoehermann/purple-signald#29]
It's fair to assume a large portion of the libpurple-signald project use it with Bitlbee, and thus are already using IRC.
Please create a channel like (`#purple-signald` or something along those lines) for it, so users / developers could interact in real time to discuss it.

Freenode / OFTC are free popular IRC networks for OSS projects.
`#signald` is already used by TheFinn93 for signald :)

**Comment by hoehermann** [comment]
Could be useful, but I have no interest in moderating an IRC channel. I probably won't even read it. Not my preferred style of communication. Feel free to set it up, I can add a link in the readme, but that is about as far as I will go.

**Comment by Strykar** [comment]
No worries, adding it to the README works equally well thank you.
I created an unofficial channel on irc.Freenode.net, named `##purple-signald`.

Note the two `##`'s, denoting it's not an official channel of the libpurple project.

Current topic is:
`Unofficial channel for https://github.com/hoehermann/libpurple-signald - A libpurple plugin for Pidgin and Bitblee. Latest release: v0.6.0 (ce98cb5)`.
I will update it to reflect new releases.
