### ISSUE TITLE
Add Installation Guide to README

### ISSUE THREAD

**Issue by Thomas131** [hoehermann/purple-signald#3]
Hi!
I really want to get signal working with Pidgin (since I thought of programming something like this on my own not knowing it already exists).

I got it installed executing the Makefile and manually copying the .so-File. (It seems like r4m0n/libpurple-signald is working on a ```make install```)

Now I am struggeling to log in. I added my Phone-Number in the +{countrycode}{number}-Style, but it seems not to work.

Generally I am also interested in contributing some time into signald, I just don't know how much time I will have. Are Pull-Requests welcome?

**Comment by hoehermann** [comment]
Regarding the log-in: As of today, this is not handled by the plug-in. I followed the instructions from [signald's Quick Start manual](https://git.callpipe.com/finn/signald#quick-start). Only after the initial set-up was done manually, I used the connection with Pidgin.

**Update:** As of v0.3.0, you can link to existing accounts.

Shortly after I published the plug-in, all of my contacts migrated to Telegram. Hence I do not actively develop this plug-in. I leave it here and am willing to maintain it for now. Pull requests are very welcome.

**Comment by jostwald** [comment]
On the subject of installation, do you know if anyone has successfully run this plugin on windows?  I haven't found any windows binaries, and my attempts to compile it on windows ran into a bunch of linux-looking library dependencies.

Thanks!

**Comment by hoehermann** [comment]
@jostwald Availability of windows builds is literally issue #1.

**Comment by jostwald** [comment]
ah, thank you

**Comment by Strykar** [comment]
A short quick start section in the README on how this integrates with signald to get users started with Bitlbee/Pidgin would be nice.

**Comment by hoehermann** [comment]
There is a short section in the [README](https://github.com/hoehermann/purple-signald#working-with-bitlbee). In case it is not sufficient, feel free to re-open this issue.
