### ISSUE TITLE
account loses registered state in signald

### ISSUE THREAD

**Issue by Strykar** [hoehermann/purple-signald#35]
A few minutes after Bitlbee starts it logs:
```
23:18 <@root> hehoe-signald - Logging in: Logged in
23:18 <@root> purple - Error: Signal Protocol - Link to Signal App - QR code creation failed:
23:18 <@root> qrencode -s 6 -o /tmp/signald_link_purple_qrcode.png 'tsdevice:/?uuid=XXXX&pub_key=XXXXXX'
23:20 <@root> purple - Error: Signal Protocol - Link to Signal App - Linking not successful!
23:20 <@root> Timed out while waiting for device to link
23:30 <@root> You're already logged in.
```
Bitlbee and libpurple-signald work fine and Group chats are loaded and function fine.

However, intermittently, it keeps logging:
```
00:18 <@root> hehoe-signald - Error: Unknown error
00:18 <@root> hehoe-signald - Signing off..
00:18 <@root> hehoe-signald - Reconnecting in 5 seconds..
00:19 <@root> hehoe-signald - Logging in: Logged in
00:19 <@root> purple - Error: Signal Protocol - Link to Signal App - QR code creation failed:
00:19 <@root> qrencode -s 6 -o /tmp/signald_link_purple_qrcode.png 'tsdevice:/?uuid=XXXX&pub_key=XXXXX'
00:20 <@root> purple - Error: Signal Protocol - Link to Signal App - Linking not successful!
00:20 <@root> Timed out while waiting for device to link
```
Signal in Bitblee appears to be working, the only change I see is I am kicked out my Signal group chats.

**Comment by hoehermann** [comment]
This seems to be related to linking. I did not write that part of the code. As far as I know, you need to open `/tmp/signald_link_purple_qrcode.png` and scan it with the official app as running on your phone.

**Comment by Strykar** [comment]
The phone number is already linked with `signald`via QR code outside of libpurple-bitlbee, `libpurple-signald` appears to be trying it again in spite of that.
Also, when I check right now, `/tmp/signald_link_purple_qrcode.png` does not exist, tho this could be a transient non-issue.

**Comment by hoehermann** [comment]
Understood. The plug-in does not properly interpret the account's state (is registered / needs linking).

**Comment by hoehermann** [comment]
I am unable to replicate this problem with Pidgin and signald version: 0.11.1. With debug output enabled, the plug-in should show a process like this:

    connecting ...
    got newline delimited message: {"type":"version","data":{…}}
    …
    Sending: {"type":"list_accounts"}
    got newline delimited message:
    {
      "type": "account_list",
      "data": {
        "accounts": [
          {
            "deviceId": 1,
            "username": "+49REDACTED",
            "filename": "/var/lib/signald/data/+49REDACTED",
            "uuid": "REDACTED",
            "registered": true,
            "has_keys": true,
            "subscribed": false
          }
        ]
      }
    }

"registered" should be "true". Can you confirm on your setup?

**Comment by Strykar** [comment]
Bitlbee reports in the IRC client:
```
10:11 <@root> hehoe-signald - Logging in: Logged in
10:11 <@root> purple - Error: Signal Protocol - Link to Signal App - QR code creation failed:
10:11 <@root> qrencode -s 6 -o /tmp/signald_link_purple_qrcode.png 'tsdevice:/?uuid=XXXX&pub_key=XXXX'
10:13 <@root> purple - Error: Signal Protocol - Link to Signal App - Linking not successful!
10:13 <@root> Timed out while waiting for device to link
```
Bitlbee debug log:
```
DEBUG account: Connecting to account +1REDACTED.
DEBUG connection: Connecting. gc = 0x5566c8c2d3b0
DEBUG prpl-hehoe-signald: login
DEBUG prpl-hehoe-signald: using local socket /var/run/signald/signald.sock
DEBUG prpl-hehoe-signald: connecting ... 0 s
DEBUG prpl-hehoe-signald: Sending: {"type":"list_accounts"}
DEBUG prpl-hehoe-signald: Sending: {"type":"subscribe","username":"+1REDACTED"}
DEBUG prpl-hehoe-signald: got newline delimited message: {"type":"version","data":{"name":"signald","version":"+git2021-01-14rcbc4fd38.0","branch":"master","commit":"cbc4fd38696c8b40bdf915bb2dc1b4c3c711a78a"}}
DEBUG prpl-hehoe-signald: received type: version
DEBUG prpl-hehoe-signald: signald version: +git2021-01-14rcbc4fd38.0
DEBUG prpl-hehoe-signald: got newline delimited message: {"type":"account_list","data":{"accounts":[{"deviceId":2,"username":"+1REDACTED","filename":"/var/lib/signald/data/+1REDACTED","uuid":"32a5f8d0-RED-ACT-ED-240fbe722ef1","registered":false,"has_keys":true,"subscribed":false}]}}
DEBUG prpl-hehoe-signald: received type: account_list
DEBUG prpl-hehoe-signald: Account +1REDACTED registered: 0
DEBUG prpl-hehoe-signald: Sending: {"type":"link"}
DEBUG prpl-hehoe-signald: Account uuid: 32a5f8d0-RED-ACT-ED-240fbe722ef1
DEBUG prpl-hehoe-signald: got newline delimited message: {"type":"subscribed"}
DEBUG prpl-hehoe-signald: received type: subscribed
DEBUG prpl-hehoe-signald: Subscribed!
DEBUG prpl-hehoe-signald: Sending: {"type":"list_contacts","username":"+1REDACTED"}
DEBUG prpl-hehoe-signald: got newline delimited message: {"type":"listen_started","data":"+1REDACTED"}
DEBUG prpl-hehoe-signald: received type: listen_started
DEBUG prpl-hehoe-signald: Ignored message of unknown type 'listen_started'.
DEBUG prpl-hehoe-signald: got newline delimited message: {"type":"linking_uri","data":{"uri":"tsdevice:/?uuid=XXXX"}}
DEBUG prpl-hehoe-signald: received type: linking_uri
DEBUG prpl-hehoe-signald: LINK URI = 'tsdevice:/?uuid=XXXX'
DEBUG util: Writing file accounts.xml to directory /var/lib/bitlbee//purple/Strykar
DEBUG util: Writing file /var/lib/bitlbee//purple/Strykar/accounts.xml
DEBUG util: Writing file blist.xml to directory /var/lib/bitlbee//purple/Strykar
DEBUG util: Writing file /var/lib/bitlbee//purple/Strykar/blist.xml
```

**Comment by hoehermann** [comment]
Thank you for providing the debug output. It is helpful. I see two problems: 

* After my changes for supporting v2 groups, the plug-in subscribed to an account before checking whether the account actually exists. 9d7b462 fixes this issue, but may negatively impact other use-cases.
* signald says, your account was created, but not registered successfully. Though I cannot tell from the documentation whether "registered" actually turns true if it is a *linked* account.

**Comment by thefinn93** [comment]
possibly related: https://gitlab.com/signald/signald/-/issues/90

**Comment by hoehermann** [comment]
Thank you for having an eye on this project's issues, too. :)

**Comment by Strykar** [comment]
@hoehermann So should I apply https://github.com/hoehermann/libpurple-signald/commit/9d7b462e4094a9af0f06c047157fd0f5fcd865be and test or just make the change to Signald's state file or both?

**Comment by hoehermann** [comment]
Changing the state file is crucial for solving this problem. I recommend using the new plug-in version, but you can do without.

**Comment by Strykar** [comment]
Changing state fixes the issue, even without updating to https://github.com/hoehermann/libpurple-signald/commit/9d7b462e4094a9af0f06c047157fd0f5fcd865be. I'll monitor for a few days and close this.

Thank you @thefinn93 and @hoehermann
