### ISSUE TITLE
Incorrect file extensions for externally served attachments

### ISSUE THREAD

**Issue by mooomooo** [hoehermann/purple-signald#39]
Splitting out the first half of #19 into its own separate bug report rather than an enhancement ( @fancypantalons ):

I think sometimes libmagic fails to detect the proper file extension (I've seen image/gif and video/mp4 attachments always result in .???). Ideally libmagic should know what extension a gif or an mp4 should be and use that, but if not, it could fall back on the provided attachment type and use the part after the / as the appropriate extension?

**Comment by hoehermann** [comment]
I did not write that part of the code. I would like the original author (you already mentioned him) to take a look at it, it would be much more efficient.

I cannot really decide whether to invest time in this plug-in or [purple-signal](https://github.com/hoehermann/purple-signal) and the pandemic has a negative impact on my motivation to do anything at all. Please do not expect this to be fixed soon.

**Comment by hoehermann** [comment]
@mooomooo Does f53a118 do anything for you?

**Comment by mooomooo** [comment]
This fixes most of the failure cases that I regularly encounter (gifs, videos, etc.) so I'd say it's pretty great.  Thanks!

However, just today I got my first text file attachments (mime types `text/plain` and `text/x-signal-plain`), which strangely also appear to not be recognized by libmagic for some reason.  This workaround is still a better solution than nothing, because `.plain` is a far more manageable extension than `.???`.  But it's not as ideal as fixing libmagic, which I can't seem to find adequate documentation for so eh.

**Comment by hoehermann** [comment]
Oh, dang, I forgot about those. I thought "oh the last part of the mime-type always is the extension. How convenient". I could parse `/etc/mime.types`, but I do not find implementing that in C too appealing right now.

**Comment by fancypantalons** [comment]
Apologies for the lack of action on this, life very much got in the way over the last few months.

I came across this library, which might be a good solve:

https://github.com/trumpowen/MegaMimes

The recommended usage is to just grab the .c and .h and drop it into the project, so maybe we can pull that in and straight up replace the use of libmagic by just going from the contentType field to a reasonable file extension.

**Comment by hoehermann** [comment]
@mooomooo This should work now. Feel free to check it out.
