### ISSUE TITLE
Bad response: 429 with libpurple-signald

### ISSUE THREAD

**Issue by heywoodlh** [hoehermann/purple-signald#40]
I am running [Bitlbee-libpurple](https://github.com/ezkrg/docker-bitlbee-libpurple) and [signald](https://hub.docker.com/u/finn/signald) in Docker containers. [The bitlbee-libpurple container builds libpurple-signald from source](https://github.com/ezkrg/docker-bitlbee-libpurple/blob/1dd49790c8f8b9514db0d672b50b8ee0247d4afc/Dockerfile#L298-L309) so I should be on the latest version of libpurple-signald.

I am running into an issue that when I attempt to turn on the hehoe-signald account through Bitlbee via libpurple-signald then Bitlbee crashes. 

Specifically when I execute `account hehoe-signald on`, Bitlbee crashes.

I get the following error logs from signald:

```
18:26:15.656 [main] INFO  io.finn.signald.Main - Binding to socket /signald/signald.sock
18:26:15.708 [main] INFO  io.finn.signald.Main - Started signald 0.12.0+git2021-02-08r98148393.17
18:27:14.102 [socketlistener] INFO  io.finn.signald.SocketHandler - Client connected
18:27:15.171 [socketlistener] INFO  manager-**********30 - Creating new manager for **********30 (stored at /signald)
18:27:17.096 [socketlistener] INFO  manager - Created a manager for **********30
18:27:17.184 [socketlistener] ERROR io.finn.signald.SocketHandler - Catching
org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Bad response: 429 
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1477) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1435) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1420) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1362) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1338) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.getContactTokenDetails(PushServiceSocket.java:782) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.getContact(SignalServiceAccountManager.java:364) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
        at io.finn.signald.Manager.getUser(Manager.java:1511) ~[signald.jar:unspecified]
        at io.finn.signald.SocketHandler.getUser(SocketHandler.java:574) ~[signald.jar:unspecified]
        at io.finn.signald.SocketHandler.handleRequest(SocketHandler.java:214) [signald.jar:unspecified]
        at io.finn.signald.SocketHandler.run(SocketHandler.java:132) [signald.jar:unspecified]
        at java.lang.Thread.run(Unknown Source) [?:?]
18:27:17.342 [socketlistener] INFO  io.finn.signald.SocketHandler - Client disconnected
18:27:17.343 [socketlistener] INFO  io.finn.signald.MessageReceiver - Last client for **********30 unsubscribed, shutting down message pipe!
```

I can send a message using the `signald.sock` socket file that is running in the finn/signald container from my Bitlbee container:

```bash
[root@arch-oryx ~]# docker exec -it bitlbee bash
bash-5.0$ nc -U /var/run/signald/signald.sock
{"type":"version","data":{"name":"signald","version":"0.12.0+git2021-02-08r98148393.17","branch":"main","commit":"9814839376b0aceed8329fecc7477a5da7d0cae8"}}
{"type": "send", "username": "+1********30", "recipientAddress": {"number": "+1********30"}, "messageBody": "Testing"}
{"type":"send_results","data":[]}
```

(FYI I just sent a test message to myself) ^^

I'm able to send and receive my message using netcat without issue:

![image](https://user-images.githubusercontent.com/18178614/107414119-cec8b780-6ace-11eb-9ab7-6ee625930256.png)

Since I'm able to interface with the `signald.sock` socket file without issue from my Bitlbee container this looks to me like an implementation issue with libpurple-signald. 

I would greatly appreciate any suggestions on how to fix this issue! :D

**Comment by heywoodlh** [comment]
For reference I also submitted an issue at the signald repository: https://gitlab.com/signald/signald/-/issues/126

**Comment by hoehermann** [comment]
Thank you for your report. Whatever happens there, an error in signald should not make the plug-in crash. I want to see if I can reproduce this in Pidgin.

Note: I recently stopped using this plug-in for myself since tinkering around with the sister-project [purple-signal](https://github.com/hoehermann/purple-signal) is more interesting. Hence I miss many bugs unless they are reported.

**Comment by hoehermann** [comment]
I am unable to reproduce this problem with Pidgin on Ubuntu. I am using the same version of signald, but I cannot forcibly trigger the "NonSuccessfulResponseCodeException" easily. Can you turn on debug logging in bitlbee? On Pidgin, this is done with the `-d` switch. Everything signald-related between `got newline delimited message: {"type":"version","data":{"name":"signald","version":"0.12.0…"}}` and the crash would be useful.

**Comment by thefinn93** [comment]
ahh I think know what this is. It seems like this is an issue with libpurple-signald calling `get_user` too frequently. That hits a heavily rate limited endpoint, it seems. [Here's another report of the same thing](https://gitlab.com/signald/signald/-/issues/114) that said they would raise it here but I don't think actually did. Is there some reason libpurple-signald is calling `get_user`?

ps. I consider the stack trace and bad error message to be a signald issue and intend to fix that at least

**Comment by hoehermann** [comment]
Hi Finn, thank you for being with me. I have no idea where that might come from. [get_user is not even mentioned in the code.](https://github.com/hoehermann/libpurple-signald/search?q=get_user)

**Comment by thefinn93** [comment]
Indeed... looks like it was [removed a month ago](https://github.com/hoehermann/libpurple-signald/commit/836e8aa7d26615af7fd95b7312173f5a8f17b481). I wonder if both of these reports are just from users on an older version of the plugin? I'm debugging with @heywoodlh on IRC right now.

**Comment by hoehermann** [comment]
Possible, but unlikely. The request for `get_user` was done once (after subscribing). That should not trigger any rate-limiting, should it not? Unless I had some other issue going on back then which caused the plug-in to unsubscribe and re-subscribe rapidly.

**Comment by thefinn93** [comment]
@heywoodlh reports on IRC that they were using [this Dockerfile](https://github.com/ezkrg/docker-bitlbee-libpurple/blob/master/Dockerfile#L291-L311), which runs `git checkout af18341` ([a commit from July 2020](https://github.com/hoehermann/libpurple-signald/commit/af1834151473e6d2cb38e0349022eaabad055877)) before building. Trying to rebuild with the latest master now.

**Comment by heywoodlh** [comment]
@hoehermann I didn't notice that `git checkout` line. I modified the Dockerfile and now I'm using master. Everything seems to be working properly using master. Sorry for the wild goose chase! 

I'll submit a PR to https://github.com/ezkrg/docker-bitlbee-libpurple and modify the Dockerfile to just use master.

**Comment by hoehermann** [comment]
All good. If possible, chose the most recent tag instead. If that is not an option, using master is okay. Sometimes I break stuff. :|

**Comment by heywoodlh** [comment]
Pull request has been submitted:  https://github.com/ezkrg/docker-bitlbee-libpurple/pull/20

**Comment by Zauberfisch** [comment]
Just had the same issue with a package from AUR. Uninstalling the package and building libpurple-signald from source fixed the problem for me.
