### ISSUE TITLE
Must send version to signald

### ISSUE THREAD

**Issue by BenWiederhake** [hoehermann/purple-signald#54]
`systemctl status signald` shows this error message over and over:

```
signald received a request with no version. This will stop working in a future version of signald. Please update your client. Client authors, see https://signald.org/articles/protocol-versioning/
```

I think it's a good idea to document this warning, and ideally fix it :D

EDIT: Earlier I talked about message loss; turns out, that was a separate issue and because I did something else wrong. The above-mentioned warning still appears, so the message loss appears to be unrelated.

**Comment by hoehermann** [comment]
This was implemented in #61. Thank you, @ttlmax.
