### ISSUE TITLE
New socket file location

### ISSUE THREAD

**Issue by thefinn93** [hoehermann/purple-signald#55]
Hello,
This is to let you know that signald is moving it's default socket file location. The old location and the new location should both be searched, as the old location isn't being deprecated any time soon.

more details in [#66](https://gitlab.com/signald/signald/-/issues/66), although what you need to know is:

>please ensure your client's default behavior when the user has not specified a different path to the socket file is to first attempt to connect to `$XDG_RUNTIME_DIR/signald/signald.sock`, then fall back to `/var/run/signald/signald.sock`.

signald has a CLI flag `--user-socket` to it to make it use the new behavior.

**Comment by hoehermann** [comment]
Thank you for the heads-up. :)

**Comment by hoehermann** [comment]
This seems to be implemented by 945eb29.
