### ISSUE TITLE
Can't see any buddies in Buddy List

### ISSUE THREAD

**Issue by rrthomas** [hoehermann/purple-signald#7]
Thanks very much for this plugin!

Using Pidgin 2.13.0 on Ubuntu 18.04, I installed the latest 0.2.0 build of the plugin in ~/.purple/plugins. (I also tried building it from git master with the same result).

When I restart Pidgin, I am able to create an account. (I notice that the account has no icon, is that normal?) It seems to connect fine. (I have previously set up signald and verified my account.)

Nothing appears in the Buddy List, however. As far as I can see, the buddy list should be updated since 0.2.0, but I can't even see a heading for Signal. Am I missing something? I can't find anything about this in `README.md` or the open or closed issues.

**Comment by demure** [comment]
Are you running the current git master of `signald` as well?

**Comment by hoehermann** [comment]
@rrthomas Can you show `pidgin -d | grep signal`?

**Comment by rrthomas** [comment]
@demure, I'm running the most recent Debian package of signald, 0.8.1+git2020-01-05r9be18958.67.

**Comment by rrthomas** [comment]
@hoehermann:

    $ pidgin -d | grep signal
    (10:59:33) plugins: probing /home/rrt/.purple/plugins/libsignald_x86_64.so
    (10:59:34) prpl-hehoe-signald: Sending: {"type":"subscribe","username":"[REDACTED]"}
    (10:59:34) prpl-hehoe-signald: Sending: {"type":"list_contacts","username":"[REDACTED]"}
    (10:59:34) prpl-hehoe-signald: got newline delimited message: {"type":"version",
    "data":{"name":"signald","version":"0.8.1+git2020-01-05r9be18958.67","branch":"master","commit":"9be18958cba7c34e7f08c97f7de496c8f6dc3602"}}
    (10:59:34) prpl-hehoe-signald: signald version: 0.8.1+git2020-01-05r9be18958.67
    (10:59:34) prpl-hehoe-signald: got newline delimited message: {"type":"subscribed"}
    (10:59:34) prpl-hehoe-signald: Subscribed!
    (10:59:34) prpl-hehoe-signald: got newline delimited message: {"type":"contact_list","data":[]}

**Comment by hoehermann** [comment]
@rrthomas: `{"type":"contact_list","data":[]}` means the contact list as supplied by signald is empty. You may want to head over to https://gitlab.com/thefinn93/signald/issues.

**Comment by rrthomas** [comment]
Thanks very much for the diagnosis!
