### ISSUE TITLE
vague instructions (wrong adduser)

### ISSUE THREAD

**Issue by dchmelik** [hoehermann/purple-signald#72]
Normally instructions are in README.txt & INSTALL.txt or .md (or no extension, but best to always have plain-text .txt despite whatever else).
```
root@cosmos:~# adduser $USER signald
- User 'root' already exists; please choose another
```

**Comment by hoehermann** [comment]
Hi David

Thank you for the report. I did not write, read or actually use the HOWTO. I guess this was meant to be a call to usermod rather than useradd. I updated the document.

Would it be better to have that information in the README? I am afraid, the readme is getting rather long.

**Comment by dchmelik** [comment]
> Would it be better to have that information in the README? I am afraid, the readme is getting rather long.

I don't know... if someone really wants to compile it they'll probably look at HOWTO so not such a big deal.  However traditionally HOWTOs were something else (than main documentation) such as informal documentation/tutorials started by The Linux Documentaion Project.
