### ISSUE TITLE
Message text when replying without "@needle: "

### ISSUE THREAD

**Issue by ttlmax** [hoehermann/purple-signald#77]
The ability to reply to messages is a great feature, thanks for that. However, wouldn't it be better to remove the "@needle: " substring in the reply? This part of the message might be confusing to the reader otherwise.

**Comment by hoehermann** [comment]
This is now implemented in 9c155ed.

By the way: Thank you for testing my dev branch. The feedback is very appreciated. ❤️

**Comment by ttlmax** [comment]
My pleasure! By this, I can use the most recent features :-)

**Comment by hoehermann** [comment]
Plus an option to enjoy my latest brain-farts until I re-base the branch so no-one finds out. ;)
