### ISSUE TITLE
want to ask about @Strykar

### ISSUE THREAD

**Issue by annhan** [hoehermann/purple-signald#78]
Hi,

 i see @Strykar in this response. 
 I want to ask that he is colleague with you.
 
thank you so much

**Comment by hoehermann** [comment]
Strykar and demure are bitlbee users who in the past gave me some helpful feedback. I have no further connection to either of them. In fact, I have not heard of any issues recently. I do not even know if they stopped using this plug-in on their servers or if it is just working alright for them.

**Comment by annhan** [comment]
thank you for your answer
