### ISSUE TITLE
Required SETTINGS preface not received

### ISSUE THREAD

**Issue by mooomooo** [hoehermann/purple-signald#80]
The plugin just recently (as of 2ish weeks ago) started dying on me with this error on two similar InternalErrors:

> Error: InternalError occurred on get_group: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.io.IOException: Required SETTINGS preface not received

> Error: InternalError occurred on list_contacts: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.io.IOException: Required SETTINGS preface not received

The only possible change might have been that I joined a new Signal group, but even that I'm not sure about.

**Comment by hoehermann** [comment]
Thank you for the report. This looks like an issue within signald. I am afraid, I cannot do anything. @thefinn93 Has there been a change in the signald API requiring the client to do some settings first?

**Comment by thefinn93** [comment]
This looks like a change to the Signal API requiring signald. I'm planning to update libsignal-service-java soon.

**Comment by thefinn93** [comment]
i don't have a specific issue for this yet, feel free to file a new one or just follow one of the existing libsignal-service-java related issues.

**Comment by hoehermann** [comment]
@mooomooo Is this still an issue or has it been resolved?

**Comment by hoehermann** [comment]
Closing due to lack of response.
